#!/bin/bash
F="deploy${1:?command}"
U="${2:-https://kubepass.sciabarra.com}/deployment/$1" 
curl -Ls "$U" >"/tmp/$F"
chmod +x /tmp/$F
sudo mv /tmp/$F /usr/local/bin/$F
sudo chown root:root /usr/local/bin/$F
shift
sudo /usr/local/bin/$F "$@"
