#cloud-config
# <script>location.href='https://github.com/sciabarracom/kubepass'</script>
runcmd:
- sysctl -p
- systemctl daemon-reload
- systemctl restart docker kubelet
- apt-mark hold kubelet kubectl kubeadm
- bash /usr/local/cloud-init.shar
- chmod +x /usr/local/bin/*
- bash /usr/local/bin/master-init
- bash /usr/local/bin/worker-init
- bash /usr/local/bin/registry-init
bootcmd:
- "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -"
- "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -"
growpart:
    mode: auto
    devices: ["/"]
manage_etc_hosts: localhost
locale: "en_US.UTF-8"
package_update: true
package_upgrade: true
package_reboot_if_required: false
apt_update: true
apt_upgrade: true
apt:
  sources:
      docker:
          keyid: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
          source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
      kubernetes:
          keyid: "54A647F9048D5688D7DA2ABE6A030B21BA07F4FB"
          source: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
packages: 
    # if you change kubernetes version...
    - kubeadm=1.14.1-00
    - kubelet=1.14.1-00
    - kubectl=1.14.1-00
    # ...also use a SUPPORTED docker version for it
    - docker-ce=18.06.2~ce~3-0~ubuntu
    - apt-transport-https
    - ntp
    - jq
    - tftp
    - arp-scan
    - apache2-utils
write_files:
  - path: /etc/kubepass_release
    content: |
      1
  - path: /etc/modules
    content: |
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack_ipv4
  - path: /etc/syctl.conf
    content: |
      net.ipv4.ip_forward=1
      net.bridge.bridge-nf-call-ip6tables=1
      net.bridge.bridge-nf-call-iptables=1
  - path: /etc/environment
    content: |
      LC_ALL=en_US.UTF-8
      LANG=en_US.UTF-8
      KUBECONFIG=/etc/kubernetes/admin.conf
  - path: /etc/docker/daemon.json
    content: |
        { 
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
        "max-size": "100m" },
        "storage-driver": "overlay2" 
        }
  - path: /usr/local/cloud-init.shar
    content: |
        cd "$(dirname $0)"
        # This is a shell archive.  Save it in a file, remove anything before
        # this line, and then unpack it by entering "sh file".  Note, it may
        # create directories; files and directories will be owned by you and
        # have default permissions.
        #
        # This archive contains:
        #
        #	bin/wait-ready
        #	bin/master-init
        #	bin/cloud-log
        #	bin/kinst
        #	bin/registry-init
        #	bin/worker-init
        #
        echo x - bin/wait-ready
        sed 's/^X//' >bin/wait-ready << 'END-of-bin/wait-ready'
        X#!/bin/bash
        XN="${1:?ready count}"
        Xcloud-init status --wait
        Xwatch sudo kubectl get nodes &
        XPID=$1
        XC="0"
        Xwhile test "$C" -lt "$N"
        Xdo C="$(sudo kubectl get nodes | awk '$2 == "Ready"' | wc -l)"   
        X   sleep 1
        Xdone
        Xkill -9 $PID
        X
        END-of-bin/wait-ready
        echo x - bin/master-init
        sed 's/^X//' >bin/master-init << 'END-of-bin/master-init'
        X#!/bin/bash
        Xif ! test "$(hostname)" == "kube-master"
        Xthen echo "I am not the kube-master" ; exit 0
        Xfi
        Xecho "*** Kubernetes Pulling Images:"
        Xkubeadm config images pull
        Xecho "*** Initializing Kubernetes:"
        Xif ! kubeadm init \
        X--apiserver-advertise-address "0.0.0.0" \
        X| tee /tmp/kubeadm.log
        Xthen exit 1
        Xfi
        Xecho "*** Installing Weave:"
        Xexport K8S_VERSION="$(kubectl version | base64 | tr -d '\n')"
        Xexport WEAVE_URL="https://cloud.weave.works/k8s/net?k8s-version=$K8S_VERSION"
        Xexport KUBECONFIG=/etc/kubernetes/admin.conf
        Xkubectl apply -f "$WEAVE_URL"
        Xecho "*** Waiting for Kubernetes to get ready:"
        XSTATE="NotReady"
        Xwhile test "$STATE" != "Ready" ; do 
        XSTATE=$(kubectl get node | tail -1 | awk '{print $2}')
        Xecho -n "." ; sleep 1
        Xdone
        Xecho ""
        Xif grep "kubeadm join" /tmp/kubeadm.log >/dev/null
        Xthen apt-get install -y tftpd-hpa
        X     kubeadm token create --ttl 0 --print-join-command >/var/lib/tftpboot/kube-join.sh
        X     systemctl start tftpd-hpa
        X     echo "Created Token and Shared with Tftp"
        Xelse echo "No join command ready - something went wrong" ; exit 1
        Xfi
        X
        END-of-bin/master-init
        echo x - bin/cloud-log
        sed 's/^X//' >bin/cloud-log << 'END-of-bin/cloud-log'
        X#!/bin/bash
        Xsudo tail -f /var/log/cloud-init-output.log
        END-of-bin/cloud-log
        echo x - bin/kinst
        sed 's/^X//' >bin/kinst << 'END-of-bin/kinst'
        X#!/bin/bash
        XF="kinst-${1:?command}"
        XU="${KINST_HOST:-https://kubepass.sciabarra.com}/kinst/$1" 
        Xcurl -Ls "$U" >"/tmp/$F"
        Xchmod +x /tmp/$F
        Xsudo mv /tmp/$F /usr/local/bin/$F
        Xsudo chown root:root /usr/local/bin/$F
        Xshift
        Xsudo /usr/local/bin/$F "$@"
        END-of-bin/kinst
        echo x - bin/registry-init
        sed 's/^X//' >bin/registry-init << 'END-of-bin/registry-init'
        X#!/bin/bash
        XCADIR=/etc/docker/certs.d/registry.k8s:5000
        Xif ! test "$(hostname)" == "kube-master"
        Xthen 
        X     echo get ca.crt /tmp/ca.crt | tftp kube-master
        X     if test -s /tmp/ca.crt
        X     then
        X       mkdir -p $CADIR
        X       mv /tmp/ca.crt $CADIR/ca.crt
        X       IP="$(grep kube-master /etc/hosts  | awk '{ print $1}')"
        X       echo "$IP registry registry.k8s" >>/etc/hosts
        X     fi
        X     exit
        Xfi
        X# preparation
        XIP=$(ip -4 addr show $(basename /sys/class/net/en*) | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
        Xecho "subjectAltName=IP:$IP" >>/etc/ssl/openssl.conf
        Xecho "$IP registry.k8s" >>/etc/hosts
        Xmkdir -p /certs /etc/docker/certs.d/registry.k8s:5000
        X# generate certs
        Xopenssl req \
        X -newkey rsa:4096 -nodes -sha256 \
        X -keyout /certs/domain.key \
        X -x509 -days 365 \
        X -out /certs/domain.crt \
        X -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=registry.k8s"
        X# make it available to docker and others
        Xcp /certs/domain.crt /etc/docker/certs.d/registry.k8s:5000/ca.crt
        Xcp /certs/domain.crt /var/lib/tftpboot/ca.crt
        X# generate htpasswd
        Xhtpasswd -B -b -n  registry password >/certs/htpasswd
        X# start docker registry
        Xdocker run -d -p 5000:5000 \
        X --restart=always --name registry \
        X -v /certs:/certs \
        X -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
        X -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
        X -e REGISTRY_AUTH=htpasswd \
        X -e REGISTRY_AUTH_HTPASSWD_REALM=basic-realm \
        X -e REGISTRY_AUTH_HTPASSWD_PATH=/certs/htpasswd \
        X registry:2
        END-of-bin/registry-init
        echo x - bin/worker-init
        sed 's/^X//' >bin/worker-init << 'END-of-bin/worker-init'
        X#!/bin/bash
        Xif test "$(hostname)" == "kube-master"
        Xthen echo "I am the master, not a worker" ; exit 0
        Xfi
        Xtest -e /tmp/kube-join.sh && rm /tmp/kube-join.sh
        Xwhile ! test -s /tmp/kube-join.sh
        Xdo sudo arp-scan -l | tail +3 | head -n -3 | awk '{ print $1 }' \
        X | while read a
        X   do echo Checking $a   
        X      echo get kube-join.sh /tmp/kube-join.sh | tftp $a
        X      if test -s /tmp/kube-join.sh
        X      then echo "$a kube-master" >>/etc/hosts
        X           break
        X      fi
        X   done
        Xdone
        Xbash /tmp/kube-join.sh
        END-of-bin/worker-init
        exit
        
