#!/bin/bash
export ROOK="https://raw.githubusercontent.com/rook/rook/release-0.9/cluster/examples/kubernetes/ceph"
kubectl apply -f "$ROOK/operator.yaml"
kubectl apply -f "$ROOK/cluster.yaml"
kubectl apply -f "$ROOK/storageclass.yaml"
kubectl patch storageclass rook-ceph-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

